services:
    timescaledb:
        image: timescale/timescaledb-ha:pg16
        restart: always
        environment:
            PGDATA: /home/postgres/data/pgdata
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_DB: ${POSTGRES_DB}
        user: '0:0'
        volumes:
            - ./data/timescaledb:/home/postgres/data
            - ./config/postgres/main.conf:/etc/postgresql/postgresql.conf
            - ./config/postgres/conf.d:/etc/postgresql/conf.d
            - ./config/postgres/pg_hba.conf:/etc/postgresql/pg_hba.conf
            - ./config/certs/server.crt:/var/lib/postgresql/server.crt
            - ./config/certs/server.key:/var/lib/postgresql/server.key
        command: ['postgres', '-c', 'config_file=/etc/postgresql/postgresql.conf', '-c', 'ssl=on', '-c', 'ssl_cert_file=/var/lib/postgresql/server.crt', '-c', 'ssl_key_file=/var/lib/postgresql/server.key']
        networks:
            - nerd-space

    pgbouncer:
        image: edoburu/pgbouncer
        restart: always
        environment:
            DATABASE_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@timescaledb:5432/${POSTGRES_DB}
            PGBOUNCER_AUTH_TYPE: md5
            PGBOUNCER_AUTH_FILE: /etc/pgbouncer/userlist.txt
            ADMIN_USERS: ${PGBOUNCER_ADMIN_USERS:-postgres}
            CLIENT_TLS_SSLMODE: require
            CLIENT_TLS_KEY_FILE: /var/lib/postgresql/server.key
            CLIENT_TLS_CERT_FILE: /var/lib/postgresql/server.crt
        user: '0:0'
        volumes:
            - ./config/userlist.txt:/etc/pgbouncer/userlist.txt
            - ./config/certs/server.crt:/var/lib/postgresql/server.crt
            - ./config/certs/server.key:/var/lib/postgresql/server.key
        ports:
            - '5432:5432'
        depends_on:
            - timescaledb
        networks:
            - nerd-space

    postgres_exporter:
        image: prometheuscommunity/postgres-exporter
        environment:
            DATA_SOURCE_URI: 'timescaledb:5432/${POSTGRES_DB}?sslmode=disable'
            DATA_SOURCE_USER: ${POSTGRES_USER}
            DATA_SOURCE_PASS: ${POSTGRES_PASSWORD}
        depends_on:
            - timescaledb
        networks:
            - nerd-space
        restart: always

    pgbouncer_exporter:
        image: prometheuscommunity/pgbouncer-exporter
        environment:
            PGBOUNCER_EXPORTER_CONNECTION_STRING: 'postgresql://${PGBOUNCER_ADMIN_USER:-postgres}:${PGBOUNCER_ADMIN_PASS}@pgbouncer:5432/pgbouncer?sslmode=disable'
        depends_on:
            - pgbouncer
        networks:
            - nerd-space
        restart: always

    prometheus:
        image: prom/prometheus
        volumes:
            - ./config/prometheus.yml:/etc/prometheus/prometheus.yml
            - ./data/prometheus:/prometheus
        user: '0:0'
        command:
            - '--config.file=/etc/prometheus/prometheus.yml'
            - '--storage.tsdb.path=/prometheus'
            - '--web.enable-lifecycle'
        restart: always
        networks:
            - nerd-space

    phppgadmin:
        image: dpage/pgadmin4:latest
        environment:
            PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
            PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
        restart: always
        networks:
            - nerd-space

    adminer:
        image: adminer
        restart: always
        networks:
           - nerd-space

networks:
    nerd-space:
        external: true
