global:
    scrape_interval: 15s
    evaluation_interval: 15s
    scrape_timeout: 10s

scrape_configs:
    - job_name: 'timescaledb'
      static_configs:
          - targets:
                - 'postgres_exporter:9187'

    - job_name: 'pgbouncer'
      static_configs:
          - targets:
                - 'pgbouncer_exporter:9127'

    - job_name: 'prometheus'
      static_configs:
          - targets:
                - 'prometheus:9090'
